# Generated by Django 6.0.2 on 2026-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclockpolicy',
            name='allow_admin_time_edits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeclockpolicy',
            name='allow_unscheduled_clock_in_when_not_strict',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeclockpolicy',
            name='grace_minutes_after_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeclockpolicy',
            name='grace_minutes_before_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeclockpolicy',
            name='require_admin_edit_reason',
            field=models.BooleanField(default=True),
        ),
    ]
