# Generated by Django 6.0.2 on 2026-02-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workshift_edit_reason_workshift_edited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_breaks', to='core.workshift')),
            ],
        ),
    ]
