# Generated by Django 6.0.2 on 2026-03-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workshift_edit_reason_workshift_edited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshift",
            name="total_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
