# Generated by Django 5.2 on 2026-04-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshift_total_time'),
        ('core', '0005_alter_mealbreak_id_alter_scheduledshift_id_and_more'),
    ]

    operations = [
    ]
